### ISSUE TITLE
Milestone due-date off by one day

### ISSUE THREAD

**Issue by bclyons12** [valeriobelli/gh-milestone#19]
**Description**
When I try to create a new milestone and assign the due-date at command line, the milestone created has a due-date on day sooner.

**Current behavior**
```Lyons% gh milestone create --title test --description 'This is a test' --due-date 2023-01-22
Creating milestone in ProjectTorreyPines/QED.jl

https://github.com/ProjectTorreyPines/QED.jl/milestone/1
Lyons% gh milestone view 1
test OPEN - 0% complete
Due by 2023-1-21 - Last updated at 2023-1-11

This is a test
```

**Expected behavior**
```
Lyons% gh milestone create --title test --description 'This is a test' --due-date 2023-01-22
Creating milestone in ProjectTorreyPines/QED.jl

https://github.com/ProjectTorreyPines/QED.jl/milestone/1
Lyons% gh milestone view 1
test OPEN - 0% complete
Due by 2023-1-22 - Last updated at 2023-1-11

This is a test
```

**Environment:**
- OS: MacOS
Installed by homebrew
gh version 2.21.2 (2023-01-03)
https://github.com/cli/cli/releases/tag/v2.21.2

**Additional information**

**Comment by valeriobelli** [comment]
Hi @bclyons12, thanks for having pointed out this issue.
I'll try to tackle it as soon as possible. 👍🏽
