### ISSUE TITLE
gh milestone view changes text color in terminal

### ISSUE THREAD

**Issue by bclyons12** [valeriobelli/gh-milestone#20]
**Description**
When I do `gh milestone view 1`, the text in the terminal changes from black to gray, which persists for following commands. Issuing another `gh milestone` command returns the font to black.

**Current behavior**
![Screen Shot 2023-01-11 at 2 04 22 PM](https://user-images.githubusercontent.com/1216060/211927741-0b28bfba-8e7b-435f-a86f-67ddd92cd3ef.png)

**Expected behavior**
Command prompt should remain in original text color

**Environment:**
- OS: MacOS
Installed by homebrew
gh version 2.21.2 (2023-01-03)
https://github.com/cli/cli/releases/tag/v2.21.2

**Additional information**

**Comment by valeriobelli** [comment]
Hi @bclyons12, thanks for having pointed out this issue. 
I'll try to tackle it as soon as possible. 👍🏽
