### ISSUE TITLE
Milestone Commands return with Bad Credentials

### ISSUE THREAD

**Issue by ndrone-kr** [valeriobelli/gh-milestone#6]
**Description**
When doing an edit or create. I get a return of bad credentials.

**Current behavior**
When doing an edit or create. I get a return of bad credentials.

**Expected behavior**
I expect them to create or edit like I can in the UI

**Environment:**
- OS: MAC 10.12.4

**Additional information**
I'm able to edit and create in the UI.

**Comment by valeriobelli** [comment]
Hey @ndrone-kr, thanks for having reported this problem and sorry for the delayed answer. GitHub hasn't notified me.

Sadly, I can't reproduce. 

Before going forward with some other debugging, may you try checking your authentication status by running `gh auth status`? It would be awesome. 😄

**Comment by valeriobelli** [comment]
Is there any chance your instance is relying only on `gh` authentication system? I'm saying so because this extension needs `GITHUB_TOKEN` to do some authenticated calls to GitHub APIs.

**Comment by ndrone-kr** [comment]
here is the result from the `gh auth status`
```
 » gh auth status 
github.com
  ✓ Logged in to github.com as ndrone-kr (/Users/ndrone-kr/.config/gh/hosts.yml)
  ✓ Git operations for github.com configured to use https protocol.
  ✓ Token: *******************
```

yes I'm relying on `gh` to handle all the authentication

**Comment by valeriobelli** [comment]
I released a new version yesterday without opening a Pull Request, sorry 😅 
Now, this extension relies on `gh` to authenticate the current user if environment variables don't include `GITHUB_TOKEN`. 

Could you give it a shot now?

**Comment by ndrone-kr** [comment]
This now works with the latest release `0.5.1`

Thanks for the fix!
