### ISSUE TITLE
List subcommand state filtering

### ISSUE THREAD

**Issue by birbilis** [valeriobelli/gh-milestone#7]
> View milestons by states (default [OPEN])

1) There's a typo here ("milestons" should be "milestones")
2) It is case sensitive (only OPEN/CLOSE, not open/close), whereas gh issues list is case insensitive when filtering for state
3) It doesn't accept ALL/all (similar to how "issues" list supports) apart from "OPEN" and "CLOSE"

**Comment by birbilis** [comment]
gh issue list -?
gives
-s, --state string       Filter by state: {open|closed|all} (default "open")

whereas
gh milestone list -?
gives
  -s, --states stringArray         View milestons by states (default [OPEN])
  
  note the use of --states instead of --state and the difference in accepted values
  also says "stringArray" instead of string, but I could find way to pass multiple values to it. Better make string and accept open/closed/all (case-insensitive) as the issue list command

**Comment by valeriobelli** [comment]
Thanks, @birbilis, for having reported those issues. They are valid observations. I'll implement them as soon as possible. 😄 

Just a comment regarding the `states` option: this name has been used to map the GraphQL type externally just for the velocity of implementation. However, as you've said, having a singular name makes the `list` subcommand simpler and aligned to the other similar subcommands (i.e., `issue list` and `pr list`).
